### ISSUE TITLE
IMG to burn to usb drive?

### ISSUE THREAD

**Issue by zanymuzik** [frederic/sabrina-custom-os#1]
Hi Frederic, 

This is amazing and I would love to try this out.
Is there a way you can provide an IMG for the SD card directly that I can use without compiling everything from scratch?

Thanks.

**Comment by frederic** [comment]
Hi,

everything is already precompiled, please see [step 1](https://github.com/frederic/sabrina-custom-os#1-write-ubuntu-image-to-usb-drive) and [step 2](https://github.com/frederic/sabrina-custom-os#2-copy-files-from-rootfs-to-system-boot-partition) to prepare an USB stick.
